# Generated by Django 4.2 on 2023-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nameDoc",
                    models.CharField(max_length=255, verbose_name="Nama Dokumen"),
                ),
                (
                    "noDoc",
                    models.CharField(max_length=25, verbose_name="Nomor Dokumen"),
                ),
                (
                    "jenisDokumen",
                    models.CharField(
                        choices=[
                            ("AJB", "Akta Jual Beli"),
                            ("SHM", "Surat Hak Milik"),
                            ("PBB", "Pajak Bumi Bangunan"),
                            ("HGB", "Hak Guna Bangunan"),
                            ("Blank", "Belum di isi"),
                        ],
                        default="Blank",
                        max_length=6,
                        verbose_name="Jenis Dokumen",
                    ),
                ),
                (
                    "alamatProperti",
                    models.CharField(
                        default="Indonesia",
                        max_length=255,
                        verbose_name="Alamat Properti atau Bangunan",
                    ),
                ),
                (
                    "ppat",
                    models.CharField(
                        max_length=255, verbose_name="Nama Notaris Tertera pada dokumen"
                    ),
                ),
                ("pdf", models.FileField(upload_to="", verbose_name="Unggah Dokumen")),
                ("body", models.CharField(max_length=200)),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Status"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Date"),
                ),
            ],
        ),
    ]
