# Generated by Django 4.2 on 2023-10-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="pdf",
            field=models.FileField(
                upload_to="store/pdfs", verbose_name="Unggah Dokumen"
            ),
        ),
    ]
