# Generated by Django 5.0 on 2023-12-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': "Sertifikat's"},
        ),
    ]
