# Generated by Django 4.2 on 2023-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="ppat",
            field=models.CharField(
                max_length=255, verbose_name="Pejabat Pembuat Akta Tanah"
            ),
        ),
    ]
